### ISSUE TITLE
Error when trying to create L1 quicklook from FIXED stare

### ISSUE THREAD

**Issue by jana-p** [mkay-atm/dl_toolbox#3]
I have tested this on two data sets. Get the error message below. Check line 1966, no "elevation" in Dataset. Similar to the other issue we had today with azimuth.

Here the output:

processing lvl1 to lvl2...
Traceback (most recent call last):
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dhara\anaconda3\Scripts\hpl2netCDF-client.exe\__main__.py", line 7, in <module>
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\command_line.py", line 86, in main
    proc_dl.bckql()
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl2netCDF_client.py", line 1966, in bckql
    azi = ds.where(ds.elevation<89, drop=True).azimuth.data
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\common.py", line 246, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'elevation'

**Comment by mkay-atm** [comment]
The files should contain an elevation variable.
- What type of scan are you trying to process?
- Could you copy/paste the information about the available data variables into this issue thread?

**Comment by jana-p** [comment]
Sorry, I didn't see this comment. I tried running FIXED stare. There is a variable called "zenith", the angle from zenith. It's probably 90 degrees minus elevation angle. I can send a full list of variables when netcdf has finished installing.

**Comment by jana-p** [comment]
Here is the full header of the L1 file.

netcdf WCS_IMO_FIXED_L1_v04_20230127 {
dimensions:
	time = 83656 ;
	range = 143 ;
	nv = 2 ;
variables:
	double dv(time, range) ;
		dv:_FillValue = -999. ;
		dv:units = "m s-1" ;
		dv:long_name = "radial velocity of scatterers away from instrument" ;
		dv:standard_name = "doppler_velocity" ;
		dv:comments = "A velocity is a vector quantity; the component of the velocity of the scatterers along the line of sight of the instrument where positive implies movement away from the instrument" ;
		dv:_CoordinateAxes = "time range" ;
	float errdv(time, range) ;
		errdv:_FillValue = -999.f ;
		errdv:units = "m s-1" ;
		errdv:long_name = "error of Doppler velocity" ;
		errdv:standard_name = "doppler_velocity_error" ;
		errdv:comments = "error of radial velocity calculated from Cramer-Rao lower bound (CRLB)" ;
		errdv:_CoordinateAxes = "time range" ;
	float intensity(time, range) ;
		intensity:_FillValue = -999.f ;
		intensity:units = "1" ;
		intensity:long_name = "backscatter intensity: b_int = snr+1, where snr denotes the signal-to-noise-ratio" ;
		intensity:standard_name = "backscatter_intensity" ;
		intensity:comments = "backscatter intensity: b_int = snr+1" ;
		intensity:_CoordinateAxes = "time range" ;
	float beta(time, range) ;
		beta:_FillValue = -999.f ;
		beta:units = "m-1 sr-1" ;
		beta:long_name = "attenuated backscatter coefficient" ;
		beta:standard_name = "volume_attenuated_backwards_scattering_function_in_air" ;
		beta:comments = "determined from SNR by means of lidar equation; uncalibrated and uncorrected" ;
		beta:_CoordinateAxes = "time range" ;
	float delv(time, range) ;
		delv:_FillValue = -999.f ;
		delv:units = "m s-1" ;
		delv:long_name = "spectral width of detected signal" ;
		delv:standard_name = "spectral_width" ;
		delv:comments = "currently not part of the standard data product" ;
		delv:_CoordinateAxes = "time range" ;
	float azi(time) ;
		azi:_FillValue = NaNf ;
		azi:units = "degree" ;
		azi:long_name = "sensor azimuth due reference point" ;
		azi:standard_name = "sensor_azimuth_angle" ;
		azi:_CoordinateAxes = "time" ;
		azi:comments = "sensor_azimuth_angle is the horizontal angle between the line of sight from the observation point to the sensor and a reference direction at the observation point, which is often due north. The angle is measured clockwise positive, starting from the reference direction. A comment attribute should be added to a data variable with this standard name to specify the reference direction. A standard name also exists for platform_azimuth_angle, where \"platform\" refers to the vehicle from which observations are made e.g. aeroplane, ship, or satellite. For some viewing geometries the sensor and the platform cannot be assumed to be close enough to neglect the difference in calculated azimuth angle." ;
	float zenith(time) ;
		zenith:_FillValue = NaNf ;
		zenith:units = "degree" ;
		zenith:long_name = "beam direction due zenith" ;
		zenith:standard_name = "zenith_angle" ;
		zenith:_CoordinateAxes = "time" ;
		zenith:comments = "zenith angle of the beam to the local vertical; a value of zero is directly overhead" ;
	float lat ;
		lat:_FillValue = -999.f ;
		lat:units = "degrees_north" ;
		lat:long_name = "latitude" ;
		lat:standard_name = "latitude" ;
		lat:comments = "latitude of sensor" ;
	float lon ;
		lon:_FillValue = -999.f ;
		lon:units = "degrees_east" ;
		lon:long_name = "longitude" ;
		lon:standard_name = "longitude" ;
		lon:comments = "longitude of sensor" ;
	float zsl ;
		zsl:_FillValue = -999.f ;
		zsl:units = "m" ;
		zsl:comments = "system altitude above mean sea level" ;
		zsl:standard_name = "altitude" ;
	float wl ;
		wl:_FillValue = -999.f ;
		wl:units = "m" ;
		wl:long_name = "laser center wavelength" ;
		wl:standard_name = "radiation_wavelength" ;
	float pd ;
		pd:_FillValue = -999.f ;
		pd:units = "seconds" ;
		pd:long_name = "laser duration" ;
		pd:comments = "duration of the transmitted pulse pd = 2 dr / c" ;
	float nfft ;
		nfft:_FillValue = -999.f ;
		nfft:units = "1" ;
		nfft:long_name = "number of fft points" ;
		nfft:comments = "according to the manufacturer" ;
	float nrg ;
		nrg:_FillValue = -999.f ;
		nrg:long_name = "total number of range gates per ray" ;
		nrg:units = "1" ;
	float lrg ;
		lrg:_FillValue = -999.f ;
		lrg:units = "m" ;
		lrg:long_name = "range gate length" ;
	float nsmpl ;
		nsmpl:_FillValue = NaNf ;
		nsmpl:long_name = "points per range gate" ;
		nsmpl:units = "1" ;
	float prf ;
		prf:_FillValue = -999.f ;
		prf:units = "s-1" ;
		prf:long_name = "pulse repetition frequency" ;
	float npls ;
		npls:_FillValue = -999.f ;
		npls:long_name = "number of pulses per ray" ;
		npls:units = "1" ;
	float focus ;
		focus:_FillValue = -999.f ;
		focus:units = "m" ;
		focus:long_name = "telescope focus length" ;
	float resv ;
		resv:_FillValue = -999.f ;
		resv:units = "m s-1" ;
		resv:long_name = "resolution of Doppler velocity" ;
	float nqf ;
		nqf:_FillValue = NaNf ;
		nqf:long_name = "nyquist frequency" ;
		nqf:comments = "half of the detector sampling frequency; detector bandwidth" ;
	float nqv ;
		nqv:_FillValue = NaNf ;
		nqv:long_name = "nyquist velocity" ;
		nqv:comments = "nq_freq*lambda/2; signal bandwidth" ;
	double smplf ;
		smplf:_FillValue = NaN ;
		smplf:long_name = "sampling frequency" ;
		smplf:units = "s-1" ;
		smplf:comments = "nsmpl / tgint" ;
	float resf ;
		resf:_FillValue = NaNf ;
		resf:long_name = "frequency resolution" ;
		resf:units = "s-1" ;
		resf:comments = "smplf / nfft" ;
	double tgint ;
		tgint:_FillValue = NaN ;
		tgint:long_name = "total observation time per range gate" ;
		tgint:units = "s" ;
		tgint:comments = "time window used for time gating the time series of the signal received on the detector: tgint = (2 X) / c, with X = range_bnds[range,1] - range_bnds[range,0]" ;
	float range_bnds(range, nv) ;
		range_bnds:_FillValue = -999.f ;
		range_bnds:units = "m" ;
	double time(time) ;
		time:_FillValue = NaN ;
		time:units = "seconds since 1970-01-01 00:00:00" ;
		time:standard_name = "time" ;
		time:long_name = "Time" ;
		time:calendar = "gregorian" ;
		time:_CoordinateAxisType = "time" ;
	float range(range) ;
		range:_FillValue = -999.f ;
		range:units = "m" ;
		range:long_name = "line of sight distance towards the center of each range gate" ;
		range:_CoordinateAxisType = "range" ;
	byte nv(nv) ;

// global attributes:
		:title = "Doppler Lidar level-X for standardized processing" ;
		:institution = "Icelandic Meteorological Office" ;
		:site_location = "N/A" ;
		:source = "ground based remote sensing" ;
		:instrument_type = "Vaisala WindCube Scan 200s" ;
		:instrument_mode = "standard" ;
		:instrument_firmware_version = " WindCube Scan 200s" ;
		:instrument_contact = "sibylle@vedur.is" ;
		:instrument_id = "N/A" ;
		:conventions = "CF-1.8" ;
		:processing_date = "2023-02-14 21:49:28.987800 UTC" ;
		:data_policy = "unrestricted use" ;
		:wigos_station_id = "N/A" ;
		:wmo_id = "N/A" ;
		:principal_investigator = "N/A" ;
		:instrument_serial_number = "27" ;
		:history = "Data processed by Dhara Consulting Services with wl2netCDF-client (for PROBE VMG) version 04 on 2023-02-14 21:49:28.987800 UTC" ;
		:comments = "no comments" ;
		:File_Configuration = "SYSTEM=windcube\nSYSTEM_ID=WLS200s-27\nSYSTEM_LONGITUDE=-21.95784\nSYSTEM_LATITUDE=63.97645\nSYSTEM_ALTITUDE=0\nUTC_offset=0\nSYSTEM_WAVELENGTH=1.552e-6\nPULS_DURATION=4.01e-7\nNUMBER_OF_GATES=143\nRANGE_GATE_LENGTH=50\nNUMBER_OF_GATE_POINTS=1\nBLINDEZONE_GATES=     0\nOVERLAPPING_GATES=0\nPULSES_PER_DIRECTION=30000\nNUMBER_OF_DIRECTIONS=4\nPULS_REPETITION_FREQ=10000.\nSCAN_TYPE=FIXED_VAD\nFOCUS=1500\nFFT_POINTS=1024\nVELOCITY_RESOLUTION=0.0382\nVERSION=04\nAVG_MIN=30\nCN_THRESHOLD=10\nCNS_RANGE=3\nCNS_PERCENTAGE=60\nSNR_THRESHOLD=0\nN_VRAD_THRESHOLD=8\nR2_THRESHOLD=0.95\nPROC_PATH=C:/Users/dhara/OneDrive/Documents/customers/PROBE/VMG_2023/data/IMO\nNC_L1_PATH=C:/Users/dhara/OneDrive/Documents/customers/PROBE/VMG_2023/data/IMO/results/LVL1\nNC_L1_BASENAME=WCS_IMO_FIXED_L1_\nNC_L2_PATH=C:/Users/dhara/OneDrive/Documents/customers/PROBE/VMG_2023/data/IMO/results/LVL2\nNC_L2_BASENAME=WCS_IMO_FIXED_L2_\nNC_L2_QL_PATH=C:/Users/dhara/OneDrive/Documents/customers/PROBE/VMG_2023/data/IMO/results/quicklooks\nNC_TITLE=Doppler Lidar level-X for standardized processing\nNC_INSTITUTION=Icelandic Meteorological Office\nNC_SITE_LOCATION=N/A\nNC_INSTRUMENT_CONTACT=sibylle@vedur.is\nNC_INSTRUMENT_ID=N/A\nNC_SOURCE=ground based remote sensing\nNC_INSTRUMENT_TYPE=Vaisala WindCube Scan 200s\nNC_INSTRUMENT_MODE=standard\nNC_INSTRUMENT_SERIAL_NUMBER=27\nNC_HISTORY=Data processed by Dhara Consulting Services with wl2netCDF-client (for PROBE VMG)\nNC_INSTRUMENT_FIRMWARE_VERSION= WindCube Scan 200s\nNC_CONVENTIONS=CF-1.8\nNC_DATA_POLICY=unrestricted use\nNC_COMMENTS=no comments\nOPERATIONAL=0\nNC_WIGOS_STATION_ID=N/A\nNC_WMO_ID=N/A\nNC_REFERENCES=E-Profile data format description\nNC_PI_ID=N/A\nNC_DATA_BLOCKING_STATUS=undefined\n" ;
}

**Comment by mkay-atm** [comment]
I implemented a fix for this issue. Let me know, if the quicklook output works.

**Comment by jana-p** [comment]
There is a new error now:

Traceback (most recent call last):
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dhara\anaconda3\Scripts\hpl2netCDF-client.exe\__main__.py", line 7, in <module>
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\command_line.py", line 86, in main
    proc_dl.bckql()
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl2netCDF_client.py", line 1976, in bckql
    azi = ds.where(ds.zenith>1, drop=True).azi.data
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\common.py", line 1291, in where
    return ops.where_method(self, cond, other)
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\ops.py", line 176, in where_method
    return apply_ufunc(
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\computation.py", line 1153, in apply_ufunc
    return apply_dataset_vfunc(
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\computation.py", line 447, in apply_dataset_vfunc
    result_vars = apply_dict_of_variables_vfunc(
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\computation.py", line 391, in apply_dict_of_variables_vfunc
    result_vars[name] = func(*variable_args)
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\computation.py", line 767, in apply_variable_ufunc
    raise ValueError(
ValueError: size of dimension 'range' on inputs was unexpectedly changed by applied function from 143 to 1. Only dimensions specified in ``exclude_dims`` with xarray.apply_ufunc are allowed to change size.

**Comment by jana-p** [comment]
This works now. Thanks for the fix. But could you also adjust the colour scale for this one? Here is an example of MeteoSwiss data, DBS plot (top) and FIXED plot (bottom):
![WCS_MeteoSwiss_ZHA_DBS_L2_bck_ql_20230101_cycle_max](https://user-images.githubusercontent.com/15358686/219324564-a062a523-22dd-43a8-98cd-43f4a3d45f38.png)
![WCS_MeteoSwiss_ZHA_FIXED_L2_bck_ql_20230101_cycle_max](https://user-images.githubusercontent.com/15358686/219324570-49f87e69-0910-4acd-9bae-0dccfeb1c765.png)

**Comment by mkay-atm** [comment]
I updated the code, changing the colorscale for windcube systems and also speeded up the backscatter plotting.

**Comment by jana-p** [comment]
Great! I'll close this.
