### ISSUE TITLE
Not enough valid directions found for DBS

### ISSUE THREAD

**Issue by jana-p** [mkay-atm/dl_toolbox#5]
I'm not sure if this is a code or a configuration issue. The code runs without error to the end. But I get the output below, when L1 data is being processed. I run this with DBS mode. DBS_TP for the same instrument on the same day works fine. There are both, DBS and DBS_TP files. Both have azimuth cycles like this: 0.0, 0.0, 180.0, 270.0, 90.0.

processing lvl1 to lvl2...
processing 'Windcube-dbs/-vad' setting!
processed 0.0 %
not enough valid directions!-->skip non-convergent time windows
some issue with the data 4 4 1672532092
processed 2.0 %
not enough valid directions!-->skip non-convergent time windows
some issue with the data 4 4 1672533786
processed 4.0 %

**Comment by mkay-atm** [comment]
1) You can check the number of valid directions in the configuration file: "N_VRAD_THRESHOLD". This is best set to 3 for DBS processing.
2) What is the time window in the configuration file, "AVG_MIN"? If there are not enough measurement in the set window, the processing will return only NaN for it and move to the next window. A larger time window can help here.
3) if "TP" is stated in the "SCAN_TYPE", only TP measurements will be used and if it not stated, only non-TP measurements are used.
