### ISSUE TITLE
Colour scale for wind

### ISSUE THREAD

**Issue by jana-p** [mkay-atm/dl_toolbox#7]
The horizontal wind product is instrument independent, and we know roughly an expected range. Therefore I suggest, to fix the colour scale min and max. The two plots below show the horizontal wind speed from two different scans of the same instrument, at the same location and same time. Top plot is VAD scan, bottom plot is DBS scan. From my experience, max of 30 or 35 m/s is reasonable.

![WCS_MeteoSwiss_Payerne_VAD_TP_L2_ql_20230101_60min](https://user-images.githubusercontent.com/15358686/219334461-df935462-5641-4ea3-b2ba-af75ccc3b94d.png)
![WCS_MeteoSwiss_Payerne_DBS_L2_ql_20230101_60min](https://user-images.githubusercontent.com/15358686/219334478-ef507aa6-5b6a-45e2-8582-eff0ac1f8b38.png)

**Comment by mkay-atm** [comment]
Currently, the clims are dynamically determined by the maximum of the windspeed encountered during the day, but i guess I could use percentiles to achieve a scaling less pronele to outliers.

**Comment by jana-p** [comment]
Ok, yes, this looks better.
