### ISSUE TITLE
Processing PPI

### ISSUE THREAD

**Issue by jana-p** [mkay-atm/dl_toolbox#8]
When running the code on PPI scan type, lvl1 file is created without error. The following error comes up when it is trying to get lvl2 data from PPI:

processing lvl1 to lvl2...
Traceback (most recent call last):
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dhara\anaconda3\Scripts\hpl2netCDF-client.exe\__main__.py", line 7, in <module>
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\command_line.py", line 82, in main
    proc_dl.dailylvl2()
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl2netCDF_client.py", line 1784, in dailylvl2
    ds_lvl2.attrs['title']= confDict['NC_TITLE']
UnboundLocalError: local variable 'ds_lvl2' referenced before assignment

**Comment by mkay-atm** [comment]
Concerning the PPIs, the Payernne data contain only sector scans and not a  full or half circle. The error you presented can be fixed easily, but at the moment, there is no sector based retrieval implemented. I suggest to add a note that PPI-LV2 products are only available for full or half circle ppi.

**Comment by jana-p** [comment]
This error is from KNMI data, which has the full circle.

**Comment by mkay-atm** [comment]
According to the individual netCDFs, I made a small correction to the code and used the following setting:
NUMBER_OF_GATES=		195
RANGE_GATE_LENGTH=		75
NUMBER_OF_DIRECTIONS=		24
SCAN_TYPE=			ppi
AVG_MIN=			30
CN_THRESHOLD=			10
CNS_RANGE=			3
CNS_PERCENTAGE=		 60
SNR_THRESHOLD=			0
N_VRAD_THRESHOLD=		12
R2_THRESHOLD=			0.95
Obtaining the following results for October, 22nd:
![sups_knmi_PPI_l2_windql_20221022_30min](https://user-images.githubusercontent.com/58219143/221860683-5a822b0e-af45-42d5-93c8-17373d481ba0.png)

**Comment by jana-p** [comment]
Yes, works for me too, on both KNMI days.
Great!
